# Generated by Django 5.0.6 on 2024-06-15 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auto",
            name="vendedor",
        ),
        migrations.RemoveField(
            model_name="auto",
            name="vendido",
        ),
        migrations.AddField(
            model_name="auto",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="auto",
            name="color",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
        migrations.AddField(
            model_name="venta",
            name="vendedor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.vendedor",
            ),
        ),
    ]
