# Generated by Django 5.0.6 on 2024-06-18 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_rename_comprador_cliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="auto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.auto"
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.vendedor"
            ),
        ),
    ]
