# Generated by Django 5.0.6 on 2024-06-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_venta_auto_alter_venta_vendedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auto",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
    ]
