# Generated by Django 5.0.6 on 2024-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_persona"),
    ]

    operations = [
        migrations.RenameField(
            model_name="persona",
            old_name="fecha_naciemiento",
            new_name="fecha_nacimiento",
        ),
        migrations.AlterField(
            model_name="persona",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
    ]
